### ISSUE TITLE
Clipping in orthographic is a bit aggressive

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#101]
Let say you want text with floating elements in front of it. 
Currently in orthographic view, there is an invisible plane that clips everything

![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/ebba3aa4-607d-4d42-8171-aaed94799857)

If you reduce the object so it doesn't clip, it gets really small

![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/4322e657-f11a-49e0-8eac-4c87277287e4)

Would be cool to support arbitrary size objects even in 2d

**Comment by hanbollar** [comment]
handled by @michaelthatsit , closing
