### ISSUE TITLE
add support for vanilla text HTMLElements within `<mr-container>`

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#118]
I played around with this while addressing the whitespace issue but it was too hairy to accomplish in a day. But ideally we should deprecated `mr-text` in favor of rendering any text HTMLElement found within the subtree of an `mr-container`.

**Comment by michaelthatsit** [comment]
Not relevant, as `mr-container is deprecated` @hanbollar

**Comment by lobau** [comment]
related to https://github.com/Volumetrics-io/mrjs/issues/420

**Comment by lobau** [comment]
we don't have mr-container anymore so we probably close this and track is somewhere else
