### ISSUE TITLE
Support for pure white and pure black text

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#133]
Probably a bug, but it's currently not possible to have pure white text / pure black text

![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/f020670d-a712-4cf7-a1e2-e2a4a3b2790b)

**Comment by michaelthatsit** [comment]
This might be something in our three js settings. I'll investigate.

**Comment by michaelthatsit** [comment]
related PR in troika text: https://github.com/protectwise/troika/pull/267
