### ISSUE TITLE
Columns are not set properly

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#160]
Each column always takes 100% of the width, so if you add 3 columns side by side, you get this

![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/5316e5f4-69db-4de8-b0ab-6e4a33313b3e)

```css
<mr-row>
    <mr-column>
        <mr-text>
            At dui pharetra adipiscing amet velit gravida in labore lectus.
        </mr-text>
    </mr-column>
    <mr-column>
        <mr-text>
            Incididunt labore sed amet vulputate est vestibulum gravida pellentesque quis.
        </mr-text>
    </mr-column>
    <mr-column>
        <mr-text>
            Cras ut sed est pulvinar at pharetra proin sed nibh.
        </mr-text>
    </mr-column>
</mr-row>
```

**Comment by michaelthatsit** [comment]
@hanbollar I had a partial fix for this but it felt like a hack, let's sync up on it. Happy for you to jump on it but I've been deeply embedded in layout the past few weeks.
