### ISSUE TITLE
Can't left-align sentences that take less than one full width

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#166]
Here is a sample code: https://codepen.io/lobau/pen/JjxaKKE/2f9b65793742a9ddd6dd34c5013e554d

This is blocking me from making any kind of text layout (like volumetrics.io landing page for example)

[Screencast from 2023-11-28 16-51-15.webm](https://github.com/Volumetrics-io/MR.js/assets/6750584/4c89905d-b66b-4f72-8551-003624ce099f)

**Comment by hanbollar** [comment]
tried it live - looks like this is working again, closing as resolved ~
