### ISSUE TITLE
Supports for inline links

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#168]
From @Dinoel27, we should support inline links in text, like `<a href="https://example.com">link</a>`

So something like
```html
<mr-text>
This is an <a href="https://example.com">example</a>.
</mr-text>
```

**Comment by Dinoel27** [comment]
I was also curious if we need/could embed iframe code? 

Here is a link to a Gaussian Splat made with Luma Labs Ai: 

<iframe src="https://lumalabs.ai/embed/a6718e60-5854-4ded-b073-12a88a461265?mode=sparkles&background=%23ffffff&color=%23000000&showTitle=true&loadBg=true&logoPosition=bottom-left&infoPosition=bottom-right&cinematicVideo=undefined&showMenu=true" width="893" height="500" frameborder="0" title="luma embed" style="border: none;"></iframe>

Could we embed this code into a page? 

And yes, here is a link I was trying to embed earlier: 
https://lumalabs.ai/embed/a6718e60-5854-4ded-b073-12a88a461265?mode=sparkles&background=%23ffffff&color=%23000000&showTitle=true&loadBg=true&logoPosition=bottom-left&infoPosition=bottom-right&cinematicVideo=undefined&showMenu=true


Thank you

**Comment by michaelthatsit** [comment]
consolidating to #214
