### ISSUE TITLE
Can't get an MR surface pure white 

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/mrjs#170]
<img width="1170" alt="Screenshot 2023-12-02 at 2 47 17 PM" src="https://github.com/Volumetrics-io/MR.js/assets/28908217/bcf95921-52ec-416b-a848-01e0ac51dfc4">

How can I get my panel pure white?

**Comment by michaelthatsit** [comment]
@hanbollar Mind if I start assigning any lighting related issues to you? seems like this is due to the default lighting issues we've discussed in the past.

**Comment by michaelthatsit** [comment]
This is actually mr-panel now, and will effect any element with a mesh associated with it.

**Comment by hanbollar** [comment]
probable fix is allow for a ‘ignore-lighting’ flag in 3d-style or just style part of css

**Comment by Dinoel27** [comment]
thank you for support 
will take a look

**Comment by hanbollar** [comment]
oh sorry @Dinoel27 i didnt mean that was a solution yet, i should have specified that that’s a probable fix i need to implement - will keep you posted for when it’s ready

**Comment by Dinoel27** [comment]
got it, thank you:)

**Comment by hanbollar** [comment]
leo noted that this is working in foodproject demo meaning the threejs bump solved this - so closing as no longer needed
