### ISSUE TITLE
seems like there's a memory leak somewhere...

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#205]
Not quite sure where it might be, but if you leave the demo running long enough on headset, we start getting WebGL warnings and some of the panels begin to flicker.

**Comment by michaelthatsit** [comment]
@hanbollar added you too it. I'll get a recording of it later.

**Comment by michaelthatsit** [comment]
@hanbollar I'm running into this something terrible with the anchoring sample. I'm 90% certain it's that we're destroying/creating geometries for UI elements. But it could also be text rendering. We should prioritized investigating this.

**Comment by hanbollar** [comment]
> @hanbollar I'm running into this something terrible with the anchoring sample. I'm 90% certain it's that we're destroying/creating geometries for UI elements. But it could also be text rendering. We should prioritized investigating this.

sg, i'll make that a top priority for me for today ~

**Comment by michaelthatsit** [comment]
<img width="1493" alt="Screenshot 2024-01-11 at 3 32 46 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19628643/57d9c4b4-af15-4251-8c98-655d4fffe199">

captured when things started freaking out. I have a video as well, waiting for my quest to finish charging so I can get it on my mac.

but the simple description is that the UIPlanes begin to flicker as the warnings start rolling in, eventually the session restarts.

**Comment by hanbollar** [comment]
> <img alt="Screenshot 2024-01-11 at 3 32 46 PM" width="1493" src="https://private-user-images.githubusercontent.com/19628643/296081490-57d9c4b4-af15-4251-8c98-655d4fffe199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMTc2NzAsIm5iZiI6MTcwNTAxNzM3MCwicGF0aCI6Ii8xOTYyODY0My8yOTYwODE0OTAtNTdkOWM0YjQtYWYxNS00MjUxLThjOTgtNjU1ZDRmZmZlMTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIzNTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZTUyNGRiYmE3YWJhNWMwMzkwODFhZjY0NzgzNjQ4OTliZDVhZDBlMDcyOGRlNDRkZWZjZTQ3NDFmZWNiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-YTv15HFL4jVayt7pm1Sc3DJyAbITY28HypTf5sAApc">
> captured when things started freaking out. I have a video as well, waiting for my quest to finish charging so I can get it on my mac.
> 
> but the simple description is that the UIPlanes begin to flicker as the warnings start rolling in, eventually the session restarts.

interesting - this might actually be part of the 'readding geometry to scene' aspect - gonna keep digging now that im on that part of optimizations

**Comment by hanbollar** [comment]
this should be fixed by #250 , leaving open until that's confirmed though

**Comment by hanbollar** [comment]
closing as fixed for now
