### ISSUE TITLE
Need to improve defaults

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#222]
This is the simplest Hello World I can create:

```html
<mr-app>
    <mr-panel>
        <mr-text>
            Hello world
        </mr-text>
    </mr-panel>
</mr-app>
```

The text should at least be readable.

https://codepen.io/lobau/pen/OJqXEVj

**Comment by michaelthatsit** [comment]
yeah looks like something is up with the default css.

**Comment by hanbollar** [comment]
@michaelthatsit @lobau - is this still needed? i think we did a rework of our defaultStyle.css already but lmk if otherwise

**Comment by lobau** [comment]
yeah I think we can close now
