### ISSUE TITLE
model in panel showing up oddly by default

### ISSUE THREAD

**Issue by hanbollar** [Volumetrics-io/mrjs#233]
<img width="701" alt="Screenshot 2024-01-11 at 4 44 43 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19377312/ccfd2204-c943-4beb-82fc-9077127e7215">

**Comment by michaelthatsit** [comment]
@hanbollar can you help me understand this one? I'm applying some CSS and a rotation to it for context, and the div it's nested in adds a collider to it, so it might be misleading.

**Comment by hanbollar** [comment]
@michaelthatsit - i had tried adding a model directly after text and also before text within a div and in both cases it didnt show up like i had expected though it had a visual box there - are there different css settings i'd have to do to have a model load in on the panel properly?

**Comment by michaelthatsit** [comment]
Ah so that's a result of css grid! no matter where you put the element it's gonna show up in the collumn set in css

<img width="513" alt="Screenshot 2024-01-16 at 4 28 43 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19628643/3da19576-1fc3-4d47-b31d-67d14e6e607a">

**Comment by hanbollar** [comment]
oooo, good to know - lemme retest again, should be good - glad i didnt scratch my head too long at this one `:D`

**Comment by hanbollar** [comment]
<img width="418" alt="Screenshot 2024-01-16 at 5 08 50 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19377312/91c83125-c70f-486c-aecd-d07479fbfa7a">
it liiiiives - yup showing up again - all good
