### ISSUE TITLE
buttons look bad while loading

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#281]
When using `mr-button`, they get very tall during loading, which look pretty weird.

[Screencast from 2024-01-23 10-18-33.webm](https://github.com/Volumetrics-io/mrjs/assets/6750584/8437390c-f8fb-45e6-86e8-b3db655bbbda)

**Comment by michaelthatsit** [comment]
What do you think of creating a loading screen for this? it's an unfortunate artifact of the text loading asynchronously.

**Comment by michaelthatsit** [comment]
It's not my favorite solution, but it's a first pass.

**Comment by lobau** [comment]
it seems it only hits buttons. Can we define their height to 0 before the loading is complete, instead of infinite, or undefined, or whatever value creates the bug?

**Comment by michaelthatsit** [comment]
That's a good idea, this is probably also caused by the height being set by the text height. All take this one up now while I wait for assets.
