### ISSUE TITLE
CSS: add support for `visibility` property

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#299]
when set to `hidden` the object should disappear.

**Comment by hanbollar** [comment]
@michaelthatsit instead of hidden, can i set it to a true/false flag

that makes more sense longer term considering opacity is also a value and there isnt any other quantity i'd expect for visibility other than hidden or not hidden (lmk if not though)

**Comment by hanbollar** [comment]
nvm i saw the css property: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
