### ISSUE TITLE
panle flashing, fps drop bug returned

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#325]
noticed it as I merged in main, we're at 30ish FPS and if left running, the panels flash and we eventually drop context.

**Comment by hanbollar** [comment]
adding note from discord - this is in MR not on desktop

**Comment by hanbollar** [comment]
@michaelthatsit i finally saw this happen in headset - it's like a weird red flickering with it, right?

only seems to happen when i leave my headset around for too long in the idle position :thinking:  - in the next sync up lets go over getting the debug log for in headset (along with the anchoring setup part) and then i'll figure it out from there

**Comment by michaelthatsit** [comment]
@hanbollar taking a further look it's definitely that the stylesystem is updating every frame for each entity, I noticed as I was figuring out this scaling bug.
