### ISSUE TITLE
3d models should not scale based on the window width

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#342]
Currently the size of 3d assets is based on the width of the window.

[Screencast from 2024-01-31 15-00-20.webm](https://github.com/Volumetrics-io/mrjs/assets/6750584/f060d8cd-142a-48c9-9171-6a8a5f04c8dc)

On 2D screens, 3D model sizes need to be fixed.

**Comment by michaelthatsit** [comment]
I will crush this bug
