### ISSUE TITLE
`mr-video` Element

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#363]
expected API

`<mr-video src="" ></mr-video>`

Spec:
- src can be local file or media stream
- player controls should be built in some how, but can be disabled
- should not require an external `video` be created somewhere else in the DOM. If needed, it should be created in the shadowDom of the custom element. See MRImage.js for reference.

**Comment by Deamoner** [comment]
I would test with a media stream. Straight video files are easy. The implementation for mediastream will be an in memory object usually set in "srcObject" so you would either need a previous created object or you create the dom element then reference it to set the object param. 
I would remember that a video panel is needed for sure but that almost any object could use a video as a mesh.

**Comment by michaelthatsit** [comment]
Reference implementation https://github.com/Volumetrics-io/mrjs/blob/main/src/core/entities/MRImage.js

**Comment by hanbollar** [comment]
closed by https://github.com/Volumetrics-io/mrjs/commit/062f98962c2ffc780ce16e7947648de2202d7a31
