### ISSUE TITLE
positioning of elements off a little bit

### ISSUE THREAD

**Issue by hanbollar** [Volumetrics-io/mrjs#372]
examples.mrjs.io/examples/index.html looks different than before

difference was caused by addition of multipanel support - https://github.com/Volumetrics-io/mrjs/pull/369

not a blocker

**Comment by hanbollar** [comment]
in #367 , after recent changes, might have a fix to do with visibility - might not be due to multipanel infighting - still noodling

**Comment by michaelthatsit** [comment]
@hanbollar I noticed this working on the physics system, changes in there should address it.

**Comment by hanbollar** [comment]
> @hanbollar I noticed this working on the physics system, changes in there should address it.

perf, good to know

**Comment by hanbollar** [comment]
still seems off on main - positioning and the z-fighting - i'll grab a visual for this

**Comment by hanbollar** [comment]
<img width="825" alt="Screenshot 2024-02-08 at 3 28 38 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19377312/92d1d9a4-9f24-4eec-97fc-ca5b146e39ed">

- [ ] image is currently resizing to container (i think this is just css fix that needs to happen) - this is also where the flickering is coming from (also css fix)

- [ ] the model shows as bumped in location even though no css changes have happened for it - not really sure why it's moved

**Comment by hanbollar** [comment]
for image resizing to container i think we're okay with that give it's a fill - but the flickering due to z-fighting im still looking into

**Comment by hanbollar** [comment]
marking as closed ~
