### ISSUE TITLE
main published example is showing up at my feet

### ISSUE THREAD

**Issue by hanbollar** [Volumetrics-io/mrjs#383]
- tried updating headset and didnt fix it
- same thing with battery and power
- going to grab the dev log later since others might hit this if their headset gets stuck in whatever odd configuration mine currently is in

-----

creating this issue as a starting point - not an issue across all users, just odd and i want to make sure it gets tracked or close in case people hit this as well in future

-----

[examples.mrjs.io](https://examples.mrjs.io)

https://github.com/Volumetrics-io/mrjs/assets/19377312/7eb48a4a-3453-42ef-8ca1-a1b70e6774eb

**Comment by hanbollar** [comment]
meta quest browser had an update changing origin of webxr - per michael: https://discord.com/channels/1137890872688660500/1137891148573200514/1205347724896112701
` OTA for the browser. Origin used to be in the middle of the room now it's the floor.`

**Comment by hanbollar** [comment]
more notes: https://discord.com/channels/1137890872688660500/1137891148573200514/1205957234656419840

```
the browser is interpetting 'local' referenceSpace as 'local-floor' for webXR sessions, making the floor the origin, so the panel appears on the ground instead of in front of the usder if it has no set anchor value.
```

**Comment by michaelthatsit** [comment]
https://github.com/mrdoob/three.js/issues/27727

**Comment by hanbollar** [comment]
since https://github.com/Volumetrics-io/mrjs/issues/389 is closed, this should be as well, closing
