### ISSUE TITLE
FPS drop, flickering, crash - debug mode

### ISSUE THREAD

**Issue by hanbollar** [Volumetrics-io/mrjs#386]
FPS drop, flickering, crash

https://github.com/Volumetrics-io/mrjs/assets/19628643/7c0ad831-51e6-406b-870c-e57e7053ea40

_Originally posted by @michaelthatsit in https://github.com/Volumetrics-io/mrjs/issues/367#issuecomment-1933436620_

------

after digging a bit on this it seems to occur when its in debug mode (where the flag exists even if set to false)

> made new bug for the crash as it seems very specific to debug mode - did enter/exit vr a few different times in a release session version and it was happy
https://github.com/Volumetrics-io/mrjs/pull/367#issuecomment-1935306944

havent found it yet for release (non debug) versions - im under the impression atm that it's more jsut the browser's ability to handle the logs and system checks as it runs too long

more digging still needed on this though

**Comment by michaelthatsit** [comment]
I experienced this with the debug flag off. it just took a little longer. but started after about 30 seconds.

**Comment by michaelthatsit** [comment]
<img width="969" alt="Screenshot 2024-02-09 at 7 54 56 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19628643/071fc164-5b8c-4360-bad5-23c0d78638e5">

Looks like the GeometrySystem is firing off more than we want it too 😬 good ole UIPlane recreation.

**Comment by hanbollar** [comment]
looks you found a short term fix with - https://github.com/Volumetrics-io/mrjs/commit/325045f93f0b3c79451335df8e9be5e76a964dc5 ?

let me know if that's true and i can look into it as part of today

**Comment by michaelthatsit** [comment]
We can close this as it's no longer an issue.
