### ISSUE TITLE
`hover-start` and `hover-end` don't trigger

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#399]
Code sample:
https://codepen.io/lobau/pen/oNVQREz

`hover-start` and `hover-end` don't trigger
only `touch-start` and `touch-end` seem to work.

Tested on:
- Firefox 122.0
- Chromium 121.0.6167.160

**Comment by michaelthatsit** [comment]
Got a fix in my bug batch. Driving to South Bay now but I'll PR what I have once I get in.

**Comment by michaelthatsit** [comment]
@lobau latest should have fixed this. please test when you get a chance.
