### ISSUE TITLE
You need to leave the entity and re-enter to retrigger `touch-start`

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#400]
Code: https://codepen.io/lobau/pen/oNVQREz

Steps to reproduce:
- click and hold on the red square. The text becomes `touch-start`
- release your finger. The text becomes `touch-end`
- click again. Nothing happens. Expectation would be that `touch-start` gets fired again

**Comment by michaelthatsit** [comment]
@lobau latest should've fixed this, please test
