### ISSUE TITLE
A better integrated testing page.

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#414]
Our current test page is outdated. We need a one stop page to test:

*Table stakes*
- performance (stats panel)
  - FPS (target 60 +)
  - latency
  - memory
- text
  - font family
  - size
  - color
- buttons
  - hover
  - click
- links
  - hover
  - click
  - image links
  - model links
- events
  - enterXR / exitXR
  - mouse events
  - touchstart / touchmove / touchend
  - hoverstart / hovermove / hoverend
  - anchored / anchor-removed
  - new-entity
  - panel-updated
  - child-updated
  - data-comp-* events
- css
  - responsiveness
  - background (color, images, etc)
  - layout
  - color
  - dimensions
  - positioning
- images
  - responsiveness
  - alt text
  - fail state
- video (to be added)
- models
  - initial size
  - type
  - texture
  - animations
- anchors
  - floating (experimental, should deprecate until it's "ready")
  - fixed
  - plane
    - labeled (floor, wall, table, door, window, none)
    - orientation (horizontal, vertical, none)
    - occlusion (true / false)
  - unanchored

*Advanced*
- ECS
  - custom entities
  - Component/Systems
- Physics
  - collisions
  - mass
  - joint constraints
- Shaders

**Comment by hanbollar** [comment]
using mrjs.io as default for this

**Comment by hanbollar** [comment]
closing since we already decided on a default
