### ISSUE TITLE
`mr-stats` element for tracking perf in XR

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#441]
Should include

- FPS
- memory
- latency
- ??

**Comment by takahirox** [comment]
It may be the easiest solution to bring the one in [WebXR samples](https://immersive-web.github.io/webxr-samples/) to MRjs if possible

**Comment by michaelthatsit** [comment]
I'd prefer to have something that looks more native to MRjs, but that should work for now. Maybe create a `stats` attribute flag in `mr-app` and then add this to the scene when it's true?

**Comment by takahirox** [comment]
> Maybe create a stats attribute flag in mr-app and then add this to the scene when it's true?

That sounds reasonable to me.

**Comment by takahirox** [comment]
By the way

```javascript
this.stats.begin();
for (const system of this.systems) {
    system._update(deltaTime, frame);
}
this.stats.end();
```

About [here](https://github.com/Volumetrics-io/mrjs/blob/0ac02418a0073f35c2dca2ea22eb98248de37d5d/src/core/MRApp.js#L471-L479), this wouldn't be better?

```
this.stats.update();
for (const system of this.systems) {
    system._update(deltaTime, frame);
}
```

If I'm right, the current one measures the systems elapsed time while the new one measures the time between two frames. It would be more accurate fps number, won't it?

**Comment by takahirox** [comment]
I started think that showing WebGL related stats in the panel to investigate the performance bottlenecks similar to A-Frame stats panel

![image](https://github.com/Volumetrics-io/mrjs/assets/7637832/9842a09b-4277-459e-925b-20245e8480bc)
