### ISSUE TITLE
`mr-a` doesn't work on mrjs.io

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#450]
Tested on both Firefox and Edge on Windows 11.

Those buttons are not clickable on https://mrjs.io

```html
<mr-a target="_blank" href="https://github.com/Volumetrics-io/mrjs">See on GitHub</mr-a>
<mr-a target="_blank" href="https://discord.gg/volumetrics">Join us on Discord</mr-a>
```

**Comment by hanbollar** [comment]
related to https://github.com/Volumetrics-io/mrjs/issues/434

**Comment by michaelthatsit** [comment]
@lobau are you using the github or npm CDN? Haven't updated NPM in a bit. We've been working to resolve the existing bugs before we push a stable version.

I believe I fixed the link bug early, having noticed it myself.

**Comment by michaelthatsit** [comment]
Ah nvm, pulled it and tested it with the latest. looks like an overlapping collider issue. I'll take it on.
