### ISSUE TITLE
Avoid additional renderer.render() calls for masking system

### ISSUE THREAD

**Issue by takahirox** [Volumetrics-io/mrjs#458]
**Problem**

Masking system seems to be one of the slowest systems in MRjs. Probably one of the reason why it's slow is currently masking system requires additional [`WebGLRenderer.render()`](https://threejs.org/docs/#api/en/renderers/WebGLRenderer.render) calls.

https://github.com/Volumetrics-io/mrjs/blob/b1f487db5497845958b6753b43478b6395e1afce/src/core/MRApp.js#L485-L494

Perhaps the additional render calls are for writing to stencil buffer but `WebGLRenderer.render()` is of course very costly because it renders an entire scene so ideally additional calls should be avoided.

**Solution**

In Three.js manner, to control rendering order for rendering objects writing to stencil buffer than other objects testing with stencil buffer it seems to be expected to use `Object3D.renderOrder` 

* https://threejs.org/docs/#api/en/core/Object3D.renderOrder
* https://github.com/mrdoob/three.js/blob/master/examples/webgl_clipping_stencil.html

By using it stencil would work with single `WebGLRenderer.render()` call.

As a test, I just commented out these lines https://github.com/Volumetrics-io/mrjs/blob/a23f983ba7c9564bfb676b95b114d6be33178fd0/src/core/MRApp.js#L484-L495 and the FPS number became 10-20% better in an example on Quest3 immersive mode while keeping masking functional (coincidentally objects writing to stencil buffer seem to be rendered earlier in my case).

**Sidenote**

Calling `this.renderer.state.buffers.stencil.setTest/Mask()` at https://github.com/Volumetrics-io/mrjs/blob/b1f487db5497845958b6753b43478b6395e1afce/src/core/MRApp.js#L485-L494 may not make sense because `WebGLRenderer` sets them in render().

**Comment by takahirox** [comment]
> In Three.js manner, to control rendering order for rendering objects writing to stencil buffer than other objects testing with stencil buffer it seems to be expected to use Object3D.renderOrder

One thing that needs to be considered would be opaque/transparent objects.

> although opaque and transparent objects remain sorted independently

https://threejs.org/docs/#api/en/core/Object3D.renderOrder

The easiest way may be setting `.transparent = true` to all the objects and we control the transparency with `.opacity` (opaque: `.opacity = 1.0`, transparent: `.opacity < 1.0`)

**Comment by takahirox** [comment]
Considering multiple panels, panel overlap, and transparency, things seem to be getting complicated. There are a few things I'd like to clarify first.

* Can panels and objects placed on them be either transparent or opaque?
* Can panels and objects placed on them be either transparent or opaque separately? (Ex: Panel is transparent, object placed on it is opaque)
* When transparent panels and their transparent objects overlap, should the objects behind be visible?

**Comment by takahirox** [comment]
I started to think that two rendering passes (but not more than two) would make the implementation simpler and maintainable if taking transparency, overlap, and rendering order into account rather than single rendering pass.

Basic idea is having two scenes (one is for stencil write and another one is for main scene graph) and separating rendering passes into stencil write pass and others (entire scene graph). (A current problem is rendering the entire scene graph twice.)

In app init
* Create two scenes, one is for stencil write (called stencil scene here) and another one is for others (called main scene here)

In masking system
* When an entity is added that can mask other elements
  * Clone a panel poly
  * Create a very simple material for the cloned poly (transparent, opacity = 0.0?)
  * Assign an unique integer id (0-) to the cloned poly
  * Set up the followings for the cloned poly
    * stencilWrite: true
    * write mask: 1 << id
    * ref: 1 << id
    * stencil func: always
    * stencil Zpass: Replace
  * Add the cloned poly to the stencil scene
* When an entity is added that can be masked by other elements
  * Find an object that can mask
  * Get the id
  * Set up the followings
    * stencilWrite: true
    * func mask: 1 << id
    * ref: 1 << id
    * stencil func: equal
    * stencil fail, zfail, zpass: keep

In animation loop
1. Update the main scene matrices
2. Copy the world matrices of masking objects in the main scene to the associated ones in the stencil scene
3. Clear stencil buffer values
4. Write to stencil buffer by rendering the stencil scene
5. Render the main scene 

One concern is stencil bits may be safe to be thought as 8 bits.

> A boolean value that indicates that the drawing buffer is requested to have a stencil buffer of at least 8 bits.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#stencil

So, with this approach the maximum number of panels (or elements that can mask other elements) would be 8. What do you think of this limitation? @michaelthatsit @hanbollar

**Comment by michaelthatsit** [comment]
> Considering multiple panels, panel overlap, and transparency, things seem to be getting complicated. There are a few things I'd like to clarify first.
> 
> * Can panels and objects placed on them be either transparent or opaque?
> * Can panels and objects placed on them be either transparent or opaque separately? (Ex: Panel is transparent, object placed on it is opaque)
> * When transparent panels and their transparent objects overlap, should the objects behind be visible?
> 
> (I guess all of them are yes, but want to clarify just in case.)

Just catching up. All of them are yes, given that the decision is ultimately in the hands of the end user.

**Comment by michaelthatsit** [comment]
> I started to think that two rendering passes (but not more than two) would make the implementation simpler and maintainable if taking transparency, overlap, and rendering order into account rather than single rendering pass.
> 
> Basic idea is having two scenes (one is for stencil write and another one is for main scene graph) and separating rendering passes into stencil write pass and others (entire scene graph). (A current problem is rendering the entire scene graph twice.)
> 
> In app init
> 
> * Create two scenes, one is for stencil write (called stencil scene here) and another one is for others (called main scene here)
> 
> In masking system
> 
> * When an entity is added that can mask other elements
>   
>   * Clone a panel poly
>   * Create a very simple material for the cloned poly (transparent, opacity = 0.0?)
>   * Assign an unique integer id (0-) to the cloned poly
>   * Set up the followings for the cloned poly
>     
>     * stencilWrite: true
>     * write mask: 1 << id
>     * ref: 1 << id
>     * stencil func: always
>     * stencil Zpass: Replace
>   * Add the cloned poly to the stencil scene
> * When an entity is added that can be masked by other elements
>   
>   * Find an object that can mask
>   * Get the id
>   * Set up the followings
>     
>     * stencilWrite: true
>     * func mask: 1 << id
>     * ref: 1 << id
>     * stencil func: equal
>     * stencil fail, zfail, zpass: keep
> 
> In animation loop
> 
> 1. Update the main scene matrices
> 2. Copy the world matrices of masking objects in the main scene to the associated ones in the stencil scene
> 3. Clear stencil buffer values
> 4. Write to stencil buffer by rendering the stencil scene
> 5. Render the main scene
> 
> One concern is stencil bits may be safe to be thought as 8 bits.
> 
> > A boolean value that indicates that the drawing buffer is requested to have a stencil buffer of at least 8 bits.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#stencil
> 
> So, with this approach the maximum number of panels (or elements that can mask other elements) would be 8. What do you think of this limitation? @michaelthatsit @hanbollar

I have a few thoughts.

- would multiple scene respond to lighting differently? i.e. the light in the light in the primary scene should effect the light in the masked scene.
- My other question comes down the physics representation and interactions. Would extra steps need to be taken in order to insure alignment between the rendered object and it's representation in the physics world?
- the 8 panel limitation is reasonable as long as we document it. Would reducing that maximum improve performance further?
