### ISSUE TITLE
Allow the ability to save the canvas as a PNG with transparency

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#506]
Sometimes it's nice to be able to right click the canvas, select "Save image as" and get a PNG of the MRjs scene, with preserved transparency.

By default, three.js doesn't preserve the drawing buffer (for performance reasons), so you have to enable it ( https://stackoverflow.com/questions/15558418/how-do-you-save-an-image-from-a-three-js-canvas )

```js
new THREE.WebGLRenderer({
    preserveDrawingBuffer: true 
});
```

It would be nice to pass it through `<mr-app>`, maybe as a boolean:

```html
<mr-app preserve-buffer="true">…</mr-app>
```

**Comment by takahirox** [comment]
Adding opt-in sounds good to me

**Comment by hanbollar** [comment]
following up from the convo here: https://github.com/Volumetrics-io/mrjs/pull/511#discussion_r1529381795

@lobau for the toggling you're requesting - is there a specific browser you were hitting your issue? i've been finding i have it by default in my setup and want to cross check why it's different than your experience

<img width="372" alt="Screenshot 2024-03-18 at 4 31 53 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19377312/d6913045-1c6d-45bf-9653-a69acf618bb9">

is it specifically about the alpha preservation?

**Comment by lobau** [comment]
@hanbollar currently if you save the image, it will be a blank PNG. The action is visible in the browser (because it's a canvas element), but the canvas element is empty.

**Comment by hanbollar** [comment]
discussed - looks like chrome and any chrome-based browsers (aka most newer ones including duckduckgo) have something inline in the chrome state s.t. save-as just works

firefox doesnt have it - using that as a good 'debugger' for this to confirm the feature with the flag works
