### ISSUE TITLE
Convert all `mr-app` attributes to `data-` attributes

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#518]
We have an increasing number of flags in mr-app. These should be converted to `data-` attributes so that they can be accessed via `this.dataset.attributeName` instead of `getAttribute`. We already use these for position, rotation, and component attributes, so we should be consistent across the board.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

ex:

`<mr-app debug="true">`

`this.getAttribute('debug')`

to

`<mr-app data-debug="true">`

`this.dataset.debug`

**Comment by michaelthatsit** [comment]
@hanbollar I've assigned this to you but feel free to delegate as you see fit.

**Comment by hanbollar** [comment]
discussion related [from @michaelthatsit on discord](https://discord.com/channels/758943204715659264/1201281972815798343/1238661434142097508):

> They should all have their own and not start with data-comp. Just data-, i.e. data-camera, data-orbital etc. That way you can use this.dataset.camera instead of getAttribute
