### ISSUE TITLE
Can't change the color of a material

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#569]
I'm trying to change both the opacity and the color of an object using Javascript.
It seems like changing the opacity works, but not the color (a change occurs, but the material becomes black)

here is an example
https://codepen.io/lobau/pen/XWQEvJZ

**Comment by hanbollar** [comment]
looking at the code real quick

**Comment by hanbollar** [comment]
the black is the background of the `mr-model` that you're seeing behind it - if you adjust the coloring of the background as well, that'll change from black->red as you're expecting

let me grab the color change function that'll help for the main object - one sec

**Comment by hanbollar** [comment]
Fixed / handled by #570
