### ISSUE TITLE
Transparent Glass CSS style only renders in debug mode  

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/mrjs#597]
Hellow,

I am working on a small prototype for myself and was trying to implement transparent UI for the app I am building.

The transparent glass css effect only renders in "debug=true" mode but doesn't show when debug is disabled. 

I am using this snippet of code for glass effect:

/* From https://css.glass */
    /* background: rgba(255,119,255, 0.3); */
    background: rgba(255, 255, 255, 0.55);
    border-radius: 16px;
    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
    /* box-shadow: 0 0px 40px rgba( 255, 119 ,255 , 2); */
    /* box-shadow: 0 4px 30px rgba( 255, 119 ,255 , 2); */
    backdrop-filter: blur(20px);
    -webkit-backdrop-filter: blur(20px);

Here is a link to the project: 
https://github.com/Dinoel27/molecules

![Frame 5](https://github.com/Volumetrics-io/mrjs/assets/28908217/cbc77215-36b7-4cd5-b23c-1d210f4c80c9)
![Frame 4](https://github.com/Volumetrics-io/mrjs/assets/28908217/4126bb73-d45c-4a1b-8be7-9e2e193b5cd4)

Any help or guidance would be greatly appreciated :)

**Comment by Dinoel27** [comment]
Resolved on my own by using mr-div wrapping the text and adding blurry background.

**Comment by michaelthatsit** [comment]
hey @Dinoel27 sorry been sick all week so I'm behind on issues. Glad you figured it out! the app is looking cool, can't wait to see the final product.
