### ISSUE TITLE
can't replay non-looping animation.

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#613]
When I setup a sound like this:

```js
mySound.components.set('audio', {
    src: "./assets/audio/sound.mp3",
    loop: false,
    action: "stop"
})
```

I can then play this sound every time I do `mySound.components.set('audio', { action: "play" })`

Unfortunately, it doesn't appear to be the case for glb animations.
If you setup an animation like:

```js
myModel.components.set('animation', {
    action: "stop",
    loop: false,
})
```

You can play the animation the same way `myModel.components.set('animation', { action: "play" })` but only once. Subsequent calls don't result in the animation being played again, regardless the status of the flag `clampWhenFinished`

**Comment by hanbollar** [comment]
[ref](https://discord.com/channels/758943204715659264/1201281972815798343/1237102438196973678)

https://codepen.io/lobau/pen/WNWVmxM
