### ISSUE TITLE
Docs: Getting started

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#92]
Our current documentation is inadequate and out dated. we need to update it. initial update should include:

- built-in elements
- layout
- text
- css
- events
- customization
  - entity
  - component/system

**Comment by lobau** [comment]
Adding lighting. I don't understand where should <mr-light> should be in the markup, how to get it to affect only certain objects, and how to disable the top-centered default white light

**Comment by michaelthatsit** [comment]
> Adding lighting. I don't understand where should should be in the markup, how to get it to affect only certain objects, and how to disable the top-centered default white light

There's a flag to disable default lighting. I'll add it to the docs.

webGL doesn't currently support per-object lighting. WebGPU does.

**Comment by lobau** [comment]
with all the work @hanbollar has put into the documentation, I think this can be fixed
